## Application Name
spring.application.name=module2Lab

## Server connection properties
server.address=127.0.0.1
server.port=8080

## Default connection pool for spring JPA defaults
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/CS600-Module2-Lab
spring.datasource.username=cs600
spring.datasource.password=cs600
